project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

lang: ja

website:
  title: "国際政治経済I@学習院2026"
  page-footer: 
    right: "@2026 Junpei Suzuki"
  sidebar:
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "シラバス"
        href: 00_syllabus.qmd
      - text: ---
      - section: イントロダクション
        contents: 
          - text: "01/はじめに"
            href: 01_intro.qmd
      - section: グローバル化
        contents: 
          - text: "02/グローバル化とは何か"
            href: 02_globalization.qmd
          - text: "03/グローバル化と国内政治"
            href: 03_domestic.qmd
          - text: "04/グローバル化と福祉国家"
            href: 04_welfare.qmd
          - text: "05/グローバル化と資本主義"
          - text: "06/地域統合"
      - section: 安全保障
        contents:
          - text: "07/経済と安全保障"
          - text: "08/リアリズム再説"
          - text: "09/リベラリズム再説"
      - section: 開発
        contents:
          - text: "10/国家の産業政策"
          - text: "11/国家の開発戦略"
          - text: "12/マクロ経済政策と国際金融"
          - text: "13/開発戦略の再編"
format:
  html:
    theme: a11y
    grid:
      sidebar-width: 250px
    number-sections: false
    toc: true
    link-external-newwindow: true

freeze: auto