---
title: "国際政治経済II"
subtitle: "学習院大学｜法学部政治学科｜2026年度第二学期｜月曜日5限"
date: 2026-09-10
date-modified: today
author:
  - name: 鈴木淳平
    affiliation: 学習院大学法学部政治学科
    email: jsuzuki@komazawa-u.ac.jp
    url: https://junpei-suzuki.github.io
---

::: callout-important
#### 注意

このページは2026年度の学習院大学法学部政治学科で開講される国際政治経済IIの最新版のシラバスおよび授業資料を兼ねたものです。現時点では未完成であり、内容には不備や誤りが含まれます。今後随時更新していきます。
:::

## 基礎情報
 - 学期：第二学期
 - 日時：月曜日5限 (17:05-18:50)
 - 場所：西2-304
 - 担当教員：鈴木淳平
     - 本務校：駒澤大学法学部政治学科
     - 連絡先：[jsuzuki@komazawa-u.ac.jp](mailto:jsuzuki@komazawa-u.ac.jp)

## 授業概要

グローバル化が進む現代、政治と経済とはますます強く結びついており、両者を分けて考えることはもはや不可能です。この科目では、そうした政治と経済の関わりについて、国際関係論の視点から考察できる能力を身につけることを目的としています。国際政治経済学の研究成果から関連する概念・理論・モデルを学び、越境する経済活動をめぐって繰り広げられる国際政治について、「印象」ではなく「根拠」に基づいて分析できる視座を提供していきます。特に第二学期の「国際政治経済I」では、第一学期で学んだことを前提に、グローバル化／地域統合や安全保障、開発といったトピックを各論的に扱います。授業では適宜アクティブラーニングを取り入れ、お互いに学び合いながら知識の習得を深めるとともに、学んだ知識を応用しながら国際政治経済を考察する経験を積めるよう手助けをしていきます。

**キーワード**：国際政治経済、国際関係論、グローバル化／地域統合、経済と安全保障、開発戦略と開発援助

## 授業計画

| 回  | 日付  | 部・到達目標       | テーマ                     | 
| --- | :---- | :----------------- | :------------------------- | 
| 1   | 9/28  | イントロダクション | [**はじめに** ](01_intro.qmd)              | 
| 2   | 10/5  | グローバル化       | [**グローバル化とは何か**](02_globalization.qmd)   | 
| 3   | 10/12 | グローバル化       | [**グローバル化と国内政治**](03_domestic.qmd) | 
| 4   | 10/19 | グローバル化       | [**グローバル化と福祉国家**](04_welfare.qmd) | 
| 5   | 10/26 | グローバル化       | [**グローバル化と資本主義**](05_capitalism.qmd) | 
| 6   | 11/16 | グローバル化       | **地域統合**               | 
| 7   | 11/23  | 安全保障           | **経済と安全保障**         | 
| 8   | 11/30 | 安全保障           | **リアリズム再説**         | 
| 9   | 12/7 | 安全保障           | **リベラリズム再説**       | 
| 10  | 12/14 | 開発               | **国家の産業政策**         | 
| 11  | 12/21  | 開発               | **国家の開発戦略**         | 
| 12  | 1/18 | 開発               | **開発戦略の再編**（補講）         | 
| 13  | N/A | 開発               | ~~**開発援助と国際金融**（補講）~~     | 